[package]
name = "trebuchet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
bitflags = "2.5.0"
bluez-async = "0.3.0"
dbus = { version = "0.9.7", features = ["futures"] }
dbus-tokio = "0.7.6"
futures = "0.3.30"
itertools = "0.12.1"
log = "0.4.21"
serde = { version = "1.0.202", features = ["derive"] }
serde-xml-rs = "0.6.0"
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["full"] }
uuid = "1.8.0"
pretty_env_logger = "0.5.0"
eyre = "0.6.12"
