[package]
name = "trebuchet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.11.5"
byteorder = "1.5.0"
clap = "4.5.4"
futures = "0.3.30"
nix = { version = "0.28.0", features = ["socket", "ioctl", "net"] }
pcap = "2.0.0"
tokio = { version = "1.37.0", features = ["full"] }
